# docker-compose.yml 抜粋
services:
  frontend:
    build: ./docker
    entrypoint: []                    # ← Node の ENTRYPOINT を無効化
    command: ["bash", "-c", "while true; do sleep 1000; done"]
    # 以下は既存と同じ
    volumes:
      - ./:/app
    working_dir: /app/frontend
    ports:
      - "5173:5173"
